version: '3.8'

services:
  app:
    container_name: lqd-banks-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:4000
      - NEXT_PUBLIC_CHAIN_ID=1
    depends_on:
      - api
      - ai-service
    networks:
      - lqd-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  api:
    container_name: lqd-banks-api
    image: lqd-banks-api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/lqdbanks
      - REDIS_URL=redis://redis:6379
      - BLOCKCHAIN_RPC_URL=${BLOCKCHAIN_RPC_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - lqd-network
    restart: always
    volumes:
      - api-logs:/app/logs

  ai-service:
    container_name: lqd-banks-ai
    image: lqd-banks-ai:latest
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PUTER_AI_API_KEY=${PUTER_AI_API_KEY}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - lqd-network
    restart: always
    volumes:
      - ai-models:/app/models
      - ai-logs:/app/logs

  postgres:
    container_name: lqd-banks-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lqdbanks
    networks:
      - lqd-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: lqd-banks-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - lqd-network
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: lqd-banks-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lqd-network
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
      - api
      - ai-service
    restart: always

networks:
  lqd-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  api-logs:
  ai-logs:
  ai-models:
